### ISSUE TITLE
Which assimp version did you use?

### ISSUE THREAD

**Issue by fxia22** [Nadrin/PBR#1]
Hi, thanks for sharing this cool project. I am wondering which assimp version are you using? I tried 3.2 and 4.1 and both versions give me some errors.

**Comment by fxia22** [comment]
Nvm I figured out, I got this error from assimp:
```
test_env_map: /home/fei/Downloads/assimp/code/Importer.cpp:759: const aiScene* Assimp::Importer::ApplyPostProcessing(unsigned int): Assertion `_ValidateFlags(pFlags)' failed.
```

after commenting out that line the assets import works. Thanks again for great work.

**Comment by Nadrin** [comment]
Hi Fei, I'm glad that you got assimp to work after all and that you find my little project useful. :) I'm planning to upgrade to assimp 4.x soon so keep an eye on the repo!

I'm closing this issue for now, if you have any more questions don't hesitate to open another one.
