### ISSUE TITLE
Missing license (file)

### ISSUE THREAD

**Issue by souljedi** [Nadrin/PBR#4]
First of all thank you for sharing your implementation on Github! For other's to contribute and also to use your implementation, it would be great if you could add a license. I know that beggars can't be choosers, but a permissive license would be most welcome.

https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by MiKom** [comment]
Hey.

License is included in `COPYING.txt` file in the root of the repository. It's MIT.

Cheers!

![image](https://user-images.githubusercontent.com/104767/65626730-38c1e900-dfce-11e9-9b5b-b84e71d7e846.png)

**Comment by souljedi** [comment]
Thanks alot! And sorry that i missed it. I was somehow narrow-minded searching for a `LICENSE.md` file and the `README.md` had no mentioning of a license either.

**Comment by MiKom** [comment]
It makes sense to have link to license file in Readme. It's more discoverable. I might create PR if I have time. Thanks!
