### ISSUE TITLE
Can't clone this project completely.

### ISSUE THREAD

**Issue by zinwalin** [Nadrin/PBR#6]
Error downloading object: data/environment.hdr (f139d4c): Smudge error: Error do wnloading data/environment.hdr (f139d4c699dc27a0b2c3a110955469b2d293e5ed94984e2d da61717a5214ce9b): batch response: This repository is over its data quota. Accou nt responsible for LFS bandwidth should purchase more data packs to restore acce ss.                                                                                                                                                               Errors logged to C:\src\PBR\.git\lfs\logs\20191122T175645.259632.log
--

**Comment by Nadrin** [comment]
All asset files have now been moved out of LFS. Git pull from master or clone the repo again to get them.
