### ISSUE TITLE
All asset data held hostage by LFS

### ISSUE THREAD

**Issue by jcoffland** [Nadrin/PBR#7]
I cannot access any of the data files.  I get this LFS error:

    This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by zinwalin** [comment]
same issue here.

**Comment by 515760058** [comment]
same issue too. 
how can I get these data files...

**Comment by Nadrin** [comment]
All asset files have now been moved out of LFS. Git pull from master or clone the repo again to get them.
