### ISSUE TITLE
Failed to load mesh file: meshes/skybox.obj

### ISSUE THREAD

**Issue by zim32** [Nadrin/PBR#8]
I compiled this project in Ubuntu 18.04, but have such error:

`./PBR 

OpenGL 4.5 Renderer [Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) ]
Compiling GLSL shader: shaders/glsl/tonemap_vs.glsl
Compiling GLSL shader: shaders/glsl/tonemap_fs.glsl
Loading mesh: meshes/skybox.obj
Assimp: Error, T0: Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there
Error: Failed to load mesh file: meshes/skybox.obj`

**Comment by Nadrin** [comment]
All asset files have now been moved out of LFS. Git pull from master or clone the repo again to get them.
