### ISSUE TITLE
Failed to load mesh file: meshes/cerberus.fbx

### ISSUE THREAD

**Issue by ychding11** [Nadrin/PBR#9]
Direct3D 11 Renderer [NVIDIA GeForce GTX 965M]
Compiling HLSL shader: shaders/hlsl/pbr.hlsl [main_ps]
Compiling HLSL shader: shaders/hlsl/pbr.hlsl [main_vs]
Compiling HLSL shader: shaders/hlsl/skybox.hlsl [main_ps]
Compiling HLSL shader: shaders/hlsl/skybox.hlsl [main_vs]
Compiling HLSL shader: shaders/hlsl/tonemap.hlsl [main_ps]
Compiling HLSL shader: shaders/hlsl/tonemap.hlsl [main_vs]
Loading mesh: meshes/cerberus.fbx
Assimp: Error, T7892: FBX-Parser (TOK_DATA, line 1, col 8) unexpected token, expected TOK_KEY
Error: Failed to load mesh file: meshes/cerberus.fbx

**Comment by ashvini-bhutare** [comment]
Can any one upload data files

**Comment by AhmadMamdouhEnan** [comment]
You can download the model from here -> http://artisaverb.info/PBT.html

**Comment by Nadrin** [comment]
All asset files have now been moved out of LFS. Git pull from master or clone the repo again to get them.
